# Attempt at to mimic kittys gruvbox dark
[colors]
foreground = "#ebdbb2"
background = "#282828"
cursor_bg = "#ebdbb2"
cursor_border = "#ebdbb2"
cursor_fg = "#1b1b1b"
selection_bg = "#3c3836"
selection_fg = "#928374"

ansi = ["#282828","#cc241d","#98971a","#d79921","#458588","#b16286","#689d6a","#a89984"]
brights = ["#928374","#fb4934","#b8bb26","#fabd2d","#83a598","#d3869b","#8ec07c","#928374"]
